name: Build with lualatex
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile main_defaultfonts.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main_defaultfonts.tex
          compiler: lualatex
          args:
      - name: biber main_defaultfonts
        uses: dante-ev/latex-action@latest
        with:
          root_file: main_defaultfonts
          compiler: biber
          args:
      - name: Compile main_defaultfonts.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main_defaultfonts.tex
          compiler: lualatex
          args:
      - name: Compile main_defaultfonts.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main_defaultfonts.tex
          compiler: lualatex
          args:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main_defaultfonts.pdf
    
